"""baseline current schema

Revision ID: 8f1f954a56bb
Revises: 
Create Date: 2026-08-31 14:05:08.674840

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f1f954a56bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_node_name'), 'alert_history', ['node_name'], unique=False)
    op.create_index(op.f('ix_alert_history_run_id'), 'alert_history', ['run_id'], unique=False)
    op.create_table('auth_session',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('incident_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_labels_node_name'), 'incident_labels', ['node_name'], unique=False)
    op.create_index(op.f('ix_incident_labels_run_id'), 'incident_labels', ['run_id'], unique=False)
    op.create_table('score_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_node_name'), 'score_history', ['node_name'], unique=False)
    op.create_index(op.f('ix_score_history_run_id'), 'score_history', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_history_run_id'), table_name='score_history')
    op.drop_index(op.f('ix_score_history_node_name'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_index(op.f('ix_incident_labels_run_id'), table_name='incident_labels')
    op.drop_index(op.f('ix_incident_labels_node_name'), table_name='incident_labels')
    op.drop_table('incident_labels')
    op.drop_table('config')
    op.drop_table('auth_session')
    op.drop_index(op.f('ix_alert_history_run_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_node_name'), table_name='alert_history')
    op.drop_table('alert_history')
    # ### end Alembic commands ###
